### ISSUE TITLE
grace apps with grace-htmx plugin fail to produce a war, run otherwise with "run-app"

### ISSUE THREAD

**Issue by jmlittle** [grace-plugins/grace-htmx#3]
Always get an error like this in the asset compile stage

Closure uglify JS Exception
asset.pipeline.processors.MinifyException: [JSC_PARSE_ERROR. Parse error. '(' expected at hyperscript.unminified.js line 85 : 24]

Tried both sample project and example gs-htmx-todomvc project. Tested with grace 2022.2.5 and 2022.1.8

**Comment by jmlittle** [comment]
If you set minifyJs to false in a project you can build a war. I suspect it should find a way to include the pre-minified version instead of attempting to reprocess the unminified in asset pipeline

**Comment by rainboyan** [comment]
@jmlittle Sorry for my late reply.

I think the errors may be related to [[Google Closure Compiler](https://developers.google.com/closure/compiler/)](https://github.com/google/closure-compiler),
but you can add the following to `build.gradle`,

```
assets {
    minifyJs = true
    minifyCss = true
    minifyOptions = [
        excludes: ['htmx.js', 'hyperscript.js'],
        languageMode: 'ES6',
        targetLanguage: 'ES6', //Can go from ES6 to ES5 for those bleeding edgers
        optimizationLevel: 'SIMPLE' //Or ADVANCED or WHITESPACE_ONLY
    ]
}
```

**Comment by jmlittle** [comment]
Thanks for the note. Probably needs to be in the docs if this is the only
way to deploy

**Comment by rainboyan** [comment]
@jmlittle I think you are right, thank you for your feedback.

There's no mention of configuration for this in the documentation, I know it from the code.
`htmx.js` and `hyperscript.js` will no longer be available in the next release, it would be more appropriate for developers to download it themselves, while also upgrading to 2.0.
